src/Entity/Librairie.php
<?php

namespace App\Entity;

use App\Repository\LibrairieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LibrairieRepository::class)
 */
class Librairie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="integer")
     */
    private $NbEmploye;

    /**
     * @ORM\Column(type="integer")
     */
    private $NbLivre;

    /**
     * @ORM\OneToMany(targetEntity=Livre::class, mappedBy="librairie", orphanRemoval=true)
     */
    private $relationships;

    public function __construct()
    {
        $this->relationships = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getNbEmploye(): ?int
    {
        return $this->NbEmploye;
    }

    public function setNbEmploye(int $NbEmploye): self
    {
        $this->NbEmploye = $NbEmploye;

        return $this;
    }

    public function getNbLivre(): ?int
    {
        return $this->NbLivre;
    }

    public function setNbLivre(int $NbLivre): self
    {
        $this->NbLivre = $NbLivre;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getRelationships(): Collection
    {
        return $this->relationships;
    }

    public function addRelationship(Livre $relationship): self
    {
        if (!$this->relationships->contains($relationship)) {
            $this->relationships[] = $relationship;
            $relationship->setLibrairie($this);
        }

        return $this;
    }

    public function removeRelationship(Livre $relationship): self
    {
        if ($this->relationships->removeElement($relationship)) {
            // set the owning side to null (unless already changed)
            if ($relationship->getLibrairie() === $this) {
                $relationship->setLibrairie(null);
            }
        }

        return $this;
    }
}

templates/articles/LivreParCategorie.html.twig
{% extends 'base.html.twig' %}
{% block title%} Liste des Livres par Catégorie{% endblock %}
{% block body %}
{{ form_start(form) }}
<div class="form-row align-items-end" >
<div class="col">
 {{ form_row(form.category) }}
</div>
 <div class="col">
 <div class="form-group">
 <button type="submit" class="btn btn-success">Rechercher</button>
 </div>
</div>
</div>
{{ form_end(form) }}
{% if livres %}
 <table id="livres" class="table table-striped">
 <thead>
 <tr>
 <th>titre</th>
 <th>auteur</th>
 <th>NbPages</th>
 <th>Catégorie</th>
 <th>Actions</th>
 </tr>
 </thead>
 <tbody>
 {% for livres in livres %}
 <tr>
 <td>{{ livre.titre }}</td>
 <td>{{ livre.auteur }}</td>
 <td>{{ livre.category.titre }}</td>
 <td>
 <a href="/livre/{{ livre.id }}" class="btn btndark">Détails</a>
 <a href="/livre/edit/{{ livre.id }}" class="btn btndark">Modifier</a>
 <a href="/livre/delete/{{ livre.id }}" class="btn btndanger" onclick="return confirm('Etesvous sûr de supprimer ce livre?');">Supprimer</a>
 </td>
 </tr>
 {% endfor %}
 </tbody>
 </table>
 {% else %}
 <p>Aucun livre</p>
 {% endif %}
{% endblock %}

templates/articles/LivresParPrix.html.twig
{% extends 'base.html.twig' %}
{% block title%} Liste des livres par prix{% endblock %}
{% block body %}
{{ form_start(form) }}
<div class="form-row align-items-end" >
<div class="col">
 {{ form_row(form.minPrice) }}
</div>
<div class="col">
 {{ form_row(form.maxPrice) }}
</div>
 <div class="col">
 <div class="form-group">
 <button type="submit" class="btn btn-success">Rechercher</button>
 </div>
</div>
</div>
{{ form_end(form) }}
{% if articles %}
 <table id="livres" class="table table-striped">
 <thead>
 <tr>
 <th>titre</th>
 <th>auteur</th>
 <th>Catégorie</th>
 <th>Actions</th>
 </tr>
 </thead>
 <tbody>
 {% for livre in articles %}
 <tr>
 <td>{{ livre.nom }}</td>
 <td>{{ livre.prix }}</td>
 <td>{{ livre.category.titre }}</td>
 <td>
 <a href="/livre/{{ livre.id }}" class="btn btndark">Détails</a>
  <a href="/livre/edit/{{ livre.id }}" class="btn btndark">Modifier</a>
 <a href="/livre/delete/{{ livre.id }}" class="btn btndanger"
 onclick="return confirm('Etesvous sûr de supprimer cet livre?');">Supprimer</a>
 </td>
 </tr>
 {% endfor %}
 </tbody>
 </table>
 {% else %}
 <p>Aucun livre</p>
 {% endif %}
{% endblock %}

templates/articles/NewLibrairie.html.twig
{% extends 'base.html.twig' %}
{% block title %}Ajouter Librairie{% endblock %}
{% block body %}
{{ form_start(form) }}
{{ form_widget(form) }}
 <button type="submit" class="btn btn-success">Créer</button>
{{ form_end(form) }}
{% endblock %}

templates/articles/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Modifier LIvre{% endblock %}
{% block body %}
{{ form_start(form) }}
{{ form_widget(form) }}
 <button type="submit" class="btn btn-success">Modifier</button>
{{ form_end(form) }}
{% endblock %}

templates/articles/index.html.twig
{% extends 'base.html.twig' %}
{% block title%} Liste des livres{% endblock %}
{% block body %}
{{ form_start(form) }}
<div class="form-row align-items-end" >
<div class="col">
 {{ form_row(form.titre) }}
</div>
 <div class="col">
 <div class="form-group">
 <button type="submit" class="btn btn-success">Rechercher</button>
 </div>
</div>
</div>
{{ form_end(form) }}
{% if livres %}
<table id="livres" class="table table-striped">
 <thead>
 <tr>
 <th>titre</th>
 <th>auteur</th>
 <th>NbPages</th>
 <th> library</th>
 <th>Actions</th>
 </tr>
 </thead>
 <tbody>
 {% for livre in articles %}
 <tr>
 <td>{{ livre.titre }}</td>
 <td>{{ livre.auteur }}</td>
 <td>{{ livre.NbPages }}</td>
  <td>{{ livre.Librairie.nom}}</td>
 <td>
 <a href="/livre/{{ livre.id }}" class="btn btn-dark">Détails</a>
<a href="/livre/edit/{{ livre.id }}" class="btn btn-dark">Modifier</a>
<a href="/livre/delete/{{ livre.id }}" class="btn btn-danger"onclick="return confirm('Etesvous sûr de supprimer cet article?');">Supprimer</a>
</td>
 </tr>
 {% endfor %}
 </tbody>
 </table>
 {% else %}
 <p>Aucun livre</p>
 {% endif %}
{% endblock %}

templates/articles/new.html.twig

{% extends 'base.html.twig' %}

{% block title %}Ajouter Livre{% endblock %}
{% block body %}
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
{{ form_widget(form) }}
<br>
 <button type="submit" class="btn btn-success">Créer</button>
{{ form_end(form) }}
{% endblock %}

templates/articles/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ Livre.titre }}{% endblock %}
{% block body %}
<h1>{{Livre.Auteur}}</h1>
<p>{{Livre.Titre }}</p>
<hr>
<a href="/">Retour</a>
{% endblock %}